export const VALIDATE_FORM = 'VALIDATE_FORM'
export const VALIDATE_FORM_SUCCESS= 'VALIDATE_FORM_SUCCESS'
export const VALIDATE_FORM_ERROR= 'VALIDATE_FORM_ERROR'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS' 
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS' 
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR' 

export const SET_PRODUCT_TO_DELETE = 'SET_PRODUCT_TO_DELETE'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'

export const GET_PRODUCT_TO_EDIT = 'SET_PRODUCT_TO_EDIT'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR'

export const START_PRODUCT_EDITION = 'START_PRODUCT_EDITION'
export const PRODUCT_EDITION_SUCCESS = 'PRODUCT_EDITION_SUCCESS'
export const PRODUCT_EDITION_ERROR = 'PRODUCT_EDITION_ERROR'